# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

dashboard:
  url: /dashboard
  param: { module: default, action: dashboard }

feed:
  url: /feed
  param: { module: feed, action: index }

api_count:
  url: /api/count.json
  param: { module: data, action: count }
  requirements:
    sf_format: json

api_rate:
  url: /api/rate.json
  param: { module: data, action: rate }
  requirements:
    sf_format: json

api_burnup:
  url: /api/burnup
  param: { module: chart, action: burnup }

api_leaderboard:
  url: /api/leaderboard
  param: { module: leaderboard, action: index }

api_report:
  url: /api/report.json
  param: { module: data, action: report }
  requirements:
    sf_format: json

api_registered:
  url: /api/registered.json
  param: { module: data, action: registered }
  requirements:
    sf_format: json

user_register:
  url: /register/:key
  param: { module: user, action: register }