<?php


/**
 * Skeleton subclass for representing a row from the 'tag' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb  5 15:36:24 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tag extends BaseTag {
    /**
     * Determine if this tag was recently scanned
     *
     * @return bool
     */
    public function wasScannedRecently() {
        return ScanLogPeer::scannedRecently($this);
    }
} // Tag
