<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tag' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb  5 15:36:24 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TagPeer extends BaseTagPeer {
    public static function getByText($text, User $user) {
        $t = new Tag();
        $t->setTag($text);
        $t->setUser($user);

        $c = $t->buildCriteria();
        if ($etag = self::doSelectOne($c)) {
            return $etag;
        } else {
            $t->save();
            return $t;
        }
    }
} // TagPeer
