propel:
  user:
    id: ~
    name:
      type: varchar
      size: 255
      required: true
      unique: true
    picture:
      type: varchar
      size: 255,
      required: true
    rfid_tag:
      type: varchar
      size: 255
      required: true
      unique: true
    created_at: ~
    
  wing:
    id: ~
    user_id:
      type: integer
      size: 11
      required: true
      foreignTable: user
      foreignReference: id
      onDelete: cascade
      onUpdate: cascade
    number:
      type: integer
      size: 11
      required: true
    created_at: ~

  feed:
    id: ~
    user_id:
      type: integer
      size: 11
      required: true
      foreignTable: user
      foreignReference: id
      onDelete: cascade
      onUpdate: cascade
    text:
      type: varchar
      size: 255
      required: true
    created_at: ~

  scan_log:
    id: ~
    tag:
      type: varchar
      size: 255
      required: true
    skipped:
      type: boolean
      required: true
      default: false
    created_at: ~